### ISSUE TITLE
How to predict future popularity once we have fitted parameters?

### ISSUE THREAD

**Issue by zhenhuascut** [canerturkmen/hawkeslib#16]
from hawkeslib import UnivariateExpHawkesProcess as UVHP

uv = UVHP()
uv.fit(t, T=3600)

Once we have fitted parameters, how to predict future popularities (e.g. after T ) as described in the paper <Modeling and Predicting Popularity Dynamics of Microblogs using Self-Excited Hawkes Processes> ? Can you provide some insights or add the functions, thanks!

**Comment by canerturkmen** [comment]
Hi @zhenhuascut, sorry for the late reply. May I ask which paper you are referring to?

**Comment by zhenhuascut** [comment]
Thanks for your response. The papers are Modeling and Predicting Popularity Dynamics of Microblogs using Self-Excited Hawkes Processes and TiDeH- Time-Dependent Hawkes Process for Predicting Retweet Dynamics. Can you update the code referring to the papers? Would be great!

**Comment by canerturkmen** [comment]
Hi @zhenhuascut, I'm sorry to say none of these models are implemented in this library (nor do I intend to do that). Maybe you can contact the authors and ask them for their code? Thanks.
